spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring_jpa?createDatabaseIfNoExist=true
    username: root
    password: Ahmed@2252300
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



logging:
  level:
    org.hibernate: info
    org.hibernate.sql: debug

